name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtual environment
        run: make venv

      - name: Unit Tests
        run: make unit_test

      - name: Integration Tests
        env:
          LOGGING_CONF_FILE: ./sample_logging.conf
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: make integration_test
